### ISSUE TITLE
The Package is not able to send reports

### ISSUE THREAD

**Issue by zakirbshaikh** [tglink/jest-email-reporter#1]
Hello,

I am new to jest-email-reporter and I completed the install as recommended also updated the config.jest but keep getting same error "Please set a from-field for jest-email-reporter in jest.config.js" can you tell me where I should be placing the jest.config.js I have it in my project folder. also when I tried to debug the code I was able to trace it back to options variable in index.js it is always blank, can you tell me what I need to do.

Regards,
Zaks

**Comment by HawkeyePierce89** [comment]
Hello, sorry for late answer, I didn't get a notification about this issue from Github.

My `jest.config.js` is

```javascript
module.exports = {
  // Automatically clear mock calls and instances between every test
  clearMocks: true,

  // Use this configuration option to add custom reporters to Jest
    reporters: [
        'default',
        ['jest-email-reporter', {
            from: 'anton@karmanov.ws',
            to: 'anton@karmanov.ws',
            subject: 'E-mail subject',
            reportIfSuccess: true,
        }]
    ],

};
```

**Comment by HawkeyePierce89** [comment]
O, I found, may be you copy configuration as is? If it is, then it won't work

I change README
